# 1. Load and Preprocess data

In [4]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import KFold

In [5]:
train = pd.read_csv('Train.csv')
test=pd.read_csv('Test.csv')
train

overall  verified   reviewTime                        reviewerID  \
0            1     False  11 12, 2016  C413C78E10E54C5DB41837889F36C1E8   
1            1      True   12 6, 2016  490AE37808EFEE3AF4FE6DEBDEB5A4C8   
2            1      True  09 17, 2014  74A9FA5A64449BEE2A2E8E3F62872F0F   
3            1      True  06 11, 2016  EB561158A2829D98B467FE03CC1E45F1   
4            1      True  12 23, 2017  5045D801332850D21618DD13A697CD9B   
...        ...       ...          ...                               ...   
29184        5      True  03 20, 2015  24A0B29940152C574DA401347CE47E7A   
29185        5      True  05 15, 2014  AD3FD1D6499FA73ACBCBB39F89EE5BF9   
29186        5      True  11 13, 2017  24C8C33C6FD8ACCAFE2EC1D1FC4DBF05   
29187        5      True   01 2, 2018  E313EE1C17E5E553343F50BBC95BB2C2   
29188        5      True  07 30, 2016  BE12BFE2E36DE2B8892B31F0BE5F997F   

                                   asin                      reviewerName  \
0      565D194F38B1CC3F806EE677C61F639C  465E154EC79AFFAB5EB2607198B21433   
1      0D66512A0A7F580523AB996378DF0F14  760C63E8E5E8DC3FAA01878D37BA5678   
2      A0E45600FF2C5A779CB4314F379C253A  C6E4DD5C1C4EC09E90182644ED6CA9EF   
3      37AB9A82470595E0ACB88BAC48C150EE  F4892A77EA45C52F40AB17ED537EF9FF   
4      5772FF30428EEB8E0258C1A53CA2EC50  522F0BBFF2B47F1D63FF781A0AB1D079   
...                                 ...                               ...   
29184  CD83ED06223FE876323282B57209D765  1B5F1A160CB115EB26D0651E5BF59BE9   
29185  3625ADD67F860057FD15B71FD0389264  C8DC85A8F6B8527735AF7FA6182BB209   
29186  0C0DF58B2AC0350731C4146D32DBD3F0  951CEFD3CA5CB6773251E773379FF26A   
29187  9C9D7AAF41631F1096FE10FBA18B6029  F5A4D2A1C2A0CAD7BBC378CB10CB410C   
29188  7A052AB86002325D7201F33FB04EB113  1DB58EA9AE6AA8E377E34CBB502A3D69   

                                              reviewText  \
0          all of the reviews for this product are fake.   
1                                 wrong part. our fault.   
2                       this wire set it really sucks!!!   
3      first use, it leaked instantly. even at 5 buck...   
4                                             didn't fit   
...                                                  ...   
29184  this is the same plush toy that the official d...   
29185  my grandson loved this. it is a great toy, he ...   
29186  my kiddo loves them! we are a rock climbing fa...   
29187  i bought this for my niece (age 2) and mailed ...   
29188  my daughter will love this! she's a huge ninja...   

                                                 summary  unixReviewTime  \
0                              All fake reviews, beware.      1478908800   
1                                               One Star      1480982400   
2                                               One Star      1410912000   
3                                               One Star      1465603200   
4                                               One Star      1513987200   
...                                                  ...             ...   
29184                        Well constructed, very soft      1426809600   
29185                                            Fun toy      1400112000   
29186   and now the play set has a nice climbing feature      1510531200   
29187  my brother said she liked it and I haven't see...      1514851200   
29188                               Ninja fan will love!      1469836800   

       vote image                                         style    category  
0       2.0   NaN                      {'Size:': ' Polaris H4'}  automotive  
1       NaN   NaN                                           NaN  automotive  
2       NaN   NaN                                           NaN  automotive  
3       NaN   NaN  {'Color:': ' Clear', 'Style:': ' 45 Degree'}  automotive  
4       NaN   NaN                                           NaN  automotive  
...     ...   ...                                           ...         ...  
2

In [6]:
train.head()

overall  verified   reviewTime                        reviewerID  \
0        1     False  11 12, 2016  C413C78E10E54C5DB41837889F36C1E8   
1        1      True   12 6, 2016  490AE37808EFEE3AF4FE6DEBDEB5A4C8   
2        1      True  09 17, 2014  74A9FA5A64449BEE2A2E8E3F62872F0F   
3        1      True  06 11, 2016  EB561158A2829D98B467FE03CC1E45F1   
4        1      True  12 23, 2017  5045D801332850D21618DD13A697CD9B   

                               asin                      reviewerName  \
0  565D194F38B1CC3F806EE677C61F639C  465E154EC79AFFAB5EB2607198B21433   
1  0D66512A0A7F580523AB996378DF0F14  760C63E8E5E8DC3FAA01878D37BA5678   
2  A0E45600FF2C5A779CB4314F379C253A  C6E4DD5C1C4EC09E90182644ED6CA9EF   
3  37AB9A82470595E0ACB88BAC48C150EE  F4892A77EA45C52F40AB17ED537EF9FF   
4  5772FF30428EEB8E0258C1A53CA2EC50  522F0BBFF2B47F1D63FF781A0AB1D079   

                                          reviewText  \
0      all of the reviews for this product are fake.   
1                             wrong part. our fault.   
2                   this wire set it really sucks!!!   
3  first use, it leaked instantly. even at 5 buck...   
4                                         didn't fit   

                     summary  unixReviewTime  vote image  \
0  All fake reviews, beware.      1478908800   2.0   NaN   
1                   One Star      1480982400   NaN   NaN   
2                   One Star      1410912000   NaN   NaN   
3                   One Star      1465603200   NaN   NaN   
4                   One Star      1513987200   NaN   NaN   

                                          style    category  
0                      {'Size:': ' Polaris H4'}  automotive  
1                                           NaN  automotive  
2                                           NaN  automotive  
3  {'Color:': ' Clear', 'Style:': ' 45 Degree'}  automotive  
4                                           NaN  automotive

preprocessing: to lower, and remove NANs, at last concatenate features.

In [7]:
def preprocess(train:pd.DataFrame):
    train=train.drop(columns=["reviewTime","reviewerID","asin","reviewerName","unixReviewTime","vote","image"])
    train['style'].fillna('')
    train['summary'].fillna('')
    train['summary']=train['summary'].astype(str)
    train['style']=train['style'].astype(str)
    train['summary'] = train['summary'].apply(lambda x: x.lower())
    train['reviewText']=train['reviewText'].apply(lambda x: x.lower())
    train['style']=train['style'].apply(lambda x: x.lower())
    train['alltext']=train['summary'].fillna('')+' '+train['reviewText'].fillna('')+' '+train['style'].fillna('')
    train['allreview']=train['summary'].fillna('')+' '+train['reviewText'].fillna('')
    return train

In [8]:
train=preprocess(train)
test = preprocess(test)
train

overall  verified                                         reviewText  \
0            1     False      all of the reviews for this product are fake.   
1            1      True                             wrong part. our fault.   
2            1      True                   this wire set it really sucks!!!   
3            1      True  first use, it leaked instantly. even at 5 buck...   
4            1      True                                         didn't fit   
...        ...       ...                                                ...   
29184        5      True  this is the same plush toy that the official d...   
29185        5      True  my grandson loved this. it is a great toy, he ...   
29186        5      True  my kiddo loves them! we are a rock climbing fa...   
29187        5      True  i bought this for my niece (age 2) and mailed ...   
29188        5      True  my daughter will love this! she's a huge ninja...   

                                                 summary  \
0                              all fake reviews, beware.   
1                                               one star   
2                                               one star   
3                                               one star   
4                                               one star   
...                                                  ...   
29184                        well constructed, very soft   
29185                                            fun toy   
29186   and now the play set has a nice climbing feature   
29187  my brother said she liked it and i haven't see...   
29188                               ninja fan will love!   

                                              style    category  \
0                          {'size:': ' polaris h4'}  automotive   
1                                               nan  automotive   
2                                               nan  automotive   
3      {'color:': ' clear', 'style:': ' 45 degree'}  automotive   
4                                               nan  automotive   
...                                             ...         ...   
29184                                           nan        toys   
29185                                           nan        toys   
29186                                           nan        toys   
29187               {'style:': ' standard version'}        toys   
29188                                           nan        toys   

                                                 alltext  \
0      all fake reviews, beware. all of the reviews f...   
1                    one star wrong part. our fault. nan   
2          one star this wire set it really sucks!!! nan   
3      one star first use, it leaked instantly. even ...   
4                                one star didn't fit nan   
...                                                  ...   
29184  well constructed, very soft this is the same p...   
29185  fun toy my grandson loved this. it is a great ...   
29186  and now the play set has a nice climbing featu...   
29187  my brother said she liked it and i haven't see...   
29188  ninja fan will love! my daughter will love thi...   

                                               allreview  
0      all fake reviews, beware. all of the reviews f...  
1                        one star wrong part. our fault.  
2              one star this wire set it really sucks!!!  
3      one star first use, it leaked instantly. even ...  
4                                    one star didn't fit  
...                                                  ...  
29184  well constructed, very soft this is the same p...  
29185  fun toy my grandson loved this. it is a great ...  
29186  and now the play set has a nice climbing featu...  
29187  my brother said she liked it and i haven't see...  
29188  ninja fan will love! my daughter will love thi...  

[29189 rows x 8 columns]

# 2. Begin to implement the binary classification model.

construct features and labels

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer,HashingVectorizer,TfidfTransformer

vectorizer = CountVectorizer(stop_words="english",max_features=4000)
transformer =TfidfTransformer()

features_bin= vectorizer.fit_transform(train["allreview"].values)
features_bin = transformer.fit_transform(features_bin)
features_bin = features_bin.toarray()
test_features_bin= vectorizer.transform(test["allreview"].values)
test_features_bin = transformer.fit_transform(test_features_bin)
test_features_bin=test_features_bin.toarray()

print(features_bin.shape,test_features_bin.shape)

labels_bin1 =  (train["overall"]>1).values.astype(np.int32)
labels_bin2 =  (train["overall"]>2).values.astype(np.int32)
labels_bin3 =  (train["overall"]>3).values.astype(np.int32)
labels_bin4 =  (train["overall"]>4).values.astype(np.int32)

(29189, 4000) (4500, 4000)


In [10]:
# PCA, uncomment this 3 lines to perform PCA analysis
#from sklearn.decomposition import PCA,TruncatedSVD

#svd = TruncatedSVD(n_components=2000)
#features = svd.fit_transform(features_bin)

In [11]:
#np.save("features2000Tfidf_bin.npy",features_bin)

In [12]:
#features = np.load("features2000Tfidf_bin.npy")

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, roc_curve, auc, f1_score,silhouette_score, adjusted_rand_score
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,VotingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.cluster import KMeans


In [14]:

def eval_mat(y_true,y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    fpr, tpr, thresholds = roc_curve(y_true, y_pred)
    roc_auc = auc(fpr, tpr)
    macro_f1 = f1_score(y_true, y_pred, average='macro')
    print("tn, fp, fn, tp:",tn, fp, fn, tp)
    print("fpr,tpr,thresholds:",fpr, tpr, thresholds)
    print("roc_auc",roc_auc)
    print("macro_f1",macro_f1)
    return tn, fp, fn, tp,fpr, tpr, thresholds,roc_auc,macro_f1

def binary_classification(model,X,y,test_file_name:str):
    # i could also use the models below, I just uncomment it.
    
    #model = DecisionTreeClassifier()
    #model = RandomForestClassifier(n_estimators=100, class_weight='balanced',verbose=1,n_jobs=20)
    #model = LogisticRegression(max_iter=300,class_weight="balanced")
    #model = svm.SVC(kernel='linear', C=1, gamma='auto')
    #model = MLPClassifier(hidden_layer_sizes=(512,256), max_iter=500, alpha=0.0001, solver='adam', random_state=0, tol=0.0001,verbose=True)
    
    # log_reg = LogisticRegression()
    #dtc = DecisionTreeClassifier(class_weight='balanced')
    #svc = SVC(kernel='linear', class_weight='balanced')
    #classifiers = [('logistic regression', log_reg), ('decision tree', dtc), ('SVM', svc)]
    #model = VotingClassifier(estimators=classifiers, voting='hard')
    
    kf = KFold(n_splits=5, shuffle=True)
    f1=[]
    for idx,(train_index, test_index) in enumerate(kf.split(X)):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        print("fold:{}".format(idx))
        tn, fp, fn, tp,fpr, tpr, thresholds,roc_auc,macro_f1=eval_mat(y_pred,y_test)
        f1.append(macro_f1)
    print("mean_f1 is :",np.mean(f1))
    test_predicted = model.predict(test_features_bin)
    test_submission = pd.DataFrame({'id':np.arange(len(test_predicted)), 'predicted':test_predicted})
    test_submission.to_csv(test_file_name, index=False)

Show the **Inbalanced** distribution

In [15]:
labels_bin1.astype(np.int32).sum()/len(labels_bin1)

0.7959162698276748

In [16]:
labels_bin2.astype(np.int32).sum()/len(labels_bin2)

0.5917640206927267

In [17]:
labels_bin3.astype(np.int32).sum()/len(labels_bin3)

0.39093494124498956

In [18]:
labels_bin4.astype(np.int32).sum()/len(labels_bin4)

0.1932919935592175

I'm trying to use GirdSearchCV or RandomizedSearchCV to find the best combination of hyperparameters, but it spend too much time.

**and it will cause ipykernel to fail.**

In [19]:
# hyperparameters = {'penalty': ['l1', 'l2', 'elasticnet', 'none'],
#               'C': [0.1, 1, 10],
#               'fit_intercept': [True, False],
#               'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
#               'multi_class': ['ovr', 'multinomial', 'auto'],
#               'class_weight': [None, 'balanced']}
# # Define the logistic regression model
# clf = LogisticRegression()

# # Perform a grid search with cross-validation to find the best hyperparameters
# search =RandomizedSearchCV(clf, hyperparameters, n_iter=100, random_state=42, cv=5, scoring='f1_macro',verbose=2,n_jobs=10)
# search.fit(features_bin, labels_bin1)

In [20]:
"""print("Best hyperparameters: ", search.best_params_)
print("Best Score: ", search.best_score_)"""

'print("Best hyperparameters: ", search.best_params_)\nprint("Best Score: ", search.best_score_)'

Apply model

In [21]:
binary_classification(LogisticRegression(max_iter=300,class_weight="balanced"),features_bin, labels_bin1,"test_submission_part_1.csv")

fold:0
tn, fp, fn, tp: 939 805 222 3872
fpr,tpr,thresholds: [0.         0.46158257 1.        ] [0.        0.9457743 1.       ] [2 1 0]
roc_auc 0.7420958675259834
macro_f1 0.76469059455242
fold:1
tn, fp, fn, tp: 961 691 255 3931
fpr,tpr,thresholds: [0.         0.41828087 1.        ] [0.         0.93908266 1.        ] [2 1 0]
roc_auc 0.7604008924016293
macro_f1 0.7813755277628934
fold:2
tn, fp, fn, tp: 944 716 271 3907
fpr,tpr,thresholds: [0.        0.4313253 1.       ] [0.         0.93513643 1.        ] [2 1 0]
roc_auc 0.7519055638542682
macro_f1 0.7722746525839455
fold:3
tn, fp, fn, tp: 935 708 243 3952
fpr,tpr,thresholds: [0.         0.43091905 1.        ] [0.        0.9420739 1.       ] [2 1 0]
roc_auc 0.755577423489837
macro_f1 0.7777442753599837
fold:4
tn, fp, fn, tp: 962 784 225 3866
fpr,tpr,thresholds: [0.         0.44902635 1.        ] [0.         0.94500122 1.        ] [2 1 0]
roc_auc 0.7479874381307501
macro_f1 0.7702753088433116
mean_f1 is : 0.7732720718205108


In [22]:
binary_classification(LogisticRegression(max_iter=300,class_weight="balanced"),features_bin,labels_bin2,"test_submission_part_2.csv")

fold:0
tn, fp, fn, tp: 1944 645 503 2746
fpr,tpr,thresholds: [0.         0.24913094 1.        ] [0.         0.84518313 1.        ] [2 1 0]
roc_auc 0.7980260973427246
macro_f1 0.7995748681780337
fold:1
tn, fp, fn, tp: 1883 718 493 2744
fpr,tpr,thresholds: [0.         0.27604767 1.        ] [0.         0.84769849 1.        ] [2 1 0]
roc_auc 0.7858254061405769
macro_f1 0.7879537408127544
fold:2
tn, fp, fn, tp: 1808 666 537 2827
fpr,tpr,thresholds: [0.         0.26919968 1.        ] [0.         0.84036861 1.        ] [2 1 0]
roc_auc 0.7855844660810118
macro_f1 0.7874609954284125
fold:3
tn, fp, fn, tp: 1881 684 466 2807
fpr,tpr,thresholds: [0.         0.26666667 1.        ] [0.         0.85762298 1.        ] [2 1 0]
roc_auc 0.7954781545982279
macro_f1 0.7979308689228469
fold:4
tn, fp, fn, tp: 1924 616 477 2820
fpr,tpr,thresholds: [0.         0.24251969 1.        ] [0.         0.85532302 1.        ] [2 1 0]
roc_auc 0.8064016679443732
macro_f1 0.8082274748162281
mean_f1 is : 0.796229589631655

In [23]:
binary_classification(LogisticRegression(solver='liblinear',
                                         penalty= 'l1',
                                         multi_class= 'ovr',
                                         max_iter= 300, 
                                         class_weight= 'balanced',
                                         C=1,
                                         random_state=1),features_bin,labels_bin3,"test_submission_part_3.csv")

fold:0
tn, fp, fn, tp: 2836 485 722 1795
fpr,tpr,thresholds: [0.         0.14604035 1.        ] [0.         0.71315058 1.        ] [2 1 0]
roc_auc 0.7835551133951282
macro_f1 0.7864614286385743
fold:1
tn, fp, fn, tp: 2894 395 684 1865
fpr,tpr,thresholds: [0.         0.12009729 1.        ] [0.         0.73165947 1.        ] [2 1 0]
roc_auc 0.8057810901466553
macro_f1 0.8092503670805822
fold:2
tn, fp, fn, tp: 2863 443 705 1827
fpr,tpr,thresholds: [0.         0.13399879 1.        ] [0.         0.72156398 1.        ] [2 1 0]
roc_auc 0.7937825954820046
macro_f1 0.7969634173133903
fold:3
tn, fp, fn, tp: 2898 427 649 1864
fpr,tpr,thresholds: [0.         0.12842105 1.        ] [0.         0.74174294 1.        ] [2 1 0]
roc_auc 0.8066609420487151
macro_f1 0.8097212838738381
fold:4
tn, fp, fn, tp: 2840 466 687 1844
fpr,tpr,thresholds: [0.         0.14095584 1.        ] [0.         0.72856578 1.        ] [2 1 0]
roc_auc 0.7938049732022258
macro_f1 0.7965430652302112
mean_f1 is : 0.799787912427319

In [24]:
hyperparameters = {'penalty': ['l2',"l1",'elasticnet'],
              'C': [0.75, 1, 1.25],
              'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
              'max_iter':[100,200,300],
              'multi_class': ['ovr'],
              'class_weight': ['balanced']}
# Define the logistic regression model
clf = LogisticRegression()

# Perform a grid search with cross-validation to find the best hyperparameters
search =RandomizedSearchCV(clf, hyperparameters, n_iter=200, cv=5, scoring='f1_macro',verbose=2,n_jobs=10)
search.fit(features_bin, labels_bin3)

Fitting 5 folds for each of 135 candidates, totalling 675 fits


/Users/xingjiandiao/Desktop/ML/lib/python3.10/site-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 135 is smaller than n_iter=200. Running 135 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/Users/xingjiandiao/Desktop/ML/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
360 fits failed out of a total of 675.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/xingjiandiao/Desktop/ML/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=200, n_jobs=10,
                   param_distributions={'C': [0.75, 1, 1.25],
                                        'class_weight': ['balanced'],
                                        'max_iter': [100, 200, 300],
                                        'multi_class': ['ovr'],
                                        'penalty': ['l2', 'l1', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='f1_macro', verbose=2)

In [25]:
print("Best hyperparameters: ", search.best_params_)
print("Best Score: ", search.best_score_)

Best hyperparameters:  {'solver': 'saga', 'penalty': 'l1', 'multi_class': 'ovr', 'max_iter': 100, 'class_weight': 'balanced', 'C': 1}
Best Score:  0.7801963230953796


In [26]:
binary_classification(LogisticRegression(max_iter=300,class_weight="balanced"),features_bin,labels_bin4,"test_submission_part_4.csv")

fold:0
tn, fp, fn, tp: 3868 287 851 832
fpr,tpr,thresholds: [0.         0.06907341 1.        ] [0.         0.49435532 1.        ] [2 1 0]
roc_auc 0.7126409561746152
macro_f1 0.7328108629062888
fold:1
tn, fp, fn, tp: 3876 251 843 868
fpr,tpr,thresholds: [0.       0.060819 1.      ] [0.         0.50730567 1.        ] [2 1 0]
roc_auc 0.7232433361746433
macro_f1 0.744877922903806
fold:2
tn, fp, fn, tp: 3838 251 866 883
fpr,tpr,thresholds: [0.        0.0613842 1.       ] [0.         0.50485992 1.        ] [2 1 0]
roc_auc 0.7217378592189982
macro_f1 0.742761748922169
fold:3
tn, fp, fn, tp: 3869 275 807 887
fpr,tpr,thresholds: [0.       0.066361 1.      ] [0.         0.52361275 1.        ] [2 1 0]
roc_auc 0.7286258735122372
macro_f1 0.7492363612111512
fold:4
tn, fp, fn, tp: 3907 267 822 841
fpr,tpr,thresholds: [0.         0.06396742 1.        ] [0.         0.50571257 1.        ] [2 1 0]
roc_auc 0.7208725751516777
macro_f1 0.742341381487059
mean_f1 is : 0.7424056554860947
[CV] END C=0.75, clas

# 3. Multiclass classification

In [27]:

labels_mc = train["overall"].values-1
features_mc = features_bin
test_features_mc = test_features_bin

In [28]:
def eval_mat(y_true,y_pred):
    confusion_mat = confusion_matrix(y_true, y_pred)
    macro_f1 = f1_score(y_true, y_pred, average='macro')
    print("confusion_mat:",confusion_mat)
    print("macro_f1",macro_f1)
    return confusion_mat,macro_f1

[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l2, solver=lbfgs; total time=  39.4s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l2, solver=liblinear; total time=   4.3s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l2, solver=sag; total time=  34.6s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l1, solver=newton-cg; total time=   1.4s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l1, solver=lbfgs; total time=   1.3s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l1, solver=liblinear; total time=   2.2s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l1, solver=sag; total time=   1.3s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l1, solver=saga; total time=  48.6s
[CV] END C=0.75, class_weight=balanced, max_iter=200, multi_class

In [30]:
def multicalss_clsfication(X,y,model,test_file_name):
    kf = KFold(n_splits=5, shuffle=True)
    for idx,(train_index, test_index) in enumerate(kf.split(X)):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        print("fold:{}".format(idx))
        eval_mat(y_pred,y_test)
    test_predicted = model.predict(test_features_bin)
    test_submission = pd.DataFrame({'id':np.arange(len(test_predicted)), 'predicted':test_predicted+1})
    test_submission.to_csv(test_file_name, index=False)

In [31]:
hyperparameters = {'penalty': ['l2',"l1",'elasticnet'],
              'C': [0.75, 1, 1.25],
              'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
              'max_iter':[100],
              'multi_class': ['multinomial'],
              'class_weight': ['balanced',None]}
# Define the logistic regression model
clf = LogisticRegression()

# Perform a grid search with cross-validation to find the best hyperparameters
search =RandomizedSearchCV(clf, hyperparameters, n_iter=200, cv=5, scoring='f1_macro',verbose=2,n_jobs=10)
search.fit(features_mc, labels_mc)

Fitting 5 folds for each of 90 candidates, totalling 450 fits


/Users/xingjiandiao/Desktop/ML/lib/python3.10/site-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 90 is smaller than n_iter=200. Running 90 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/Users/xingjiandiao/Desktop/ML/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/xingjiandiao/Desktop/ML/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase t

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=200, n_jobs=10,
                   param_distributions={'C': [0.75, 1, 1.25],
                                        'class_weight': ['balanced', None],
                                        'max_iter': [100],
                                        'multi_class': ['multinomial'],
                                        'penalty': ['l2', 'l1', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='f1_macro', verbose=2)

In [32]:
print("Best hyperparameters: ", search.best_params_)
print("Best Score: ", search.best_score_)

Best hyperparameters:  {'solver': 'newton-cg', 'penalty': 'l2', 'multi_class': 'multinomial', 'max_iter': 100, 'class_weight': None, 'C': 0.75}
Best Score:  0.47902595968920886
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l2, solver=newton-cg; total time= 1.1min
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=l2, solver=saga; total time=  24.1s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=elasticnet, solver=newton-cg; total time=   1.3s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=elasticnet, solver=lbfgs; total time=   1.3s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=elasticnet, solver=liblinear; total time=   1.3s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=elasticnet, solver=sag; total time=   1.3s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=ovr, penalty=elastic

In [33]:
multicalss_clsfication(features_mc,
                       labels_mc,
                       LogisticRegression(max_iter=100,
                                          class_weight=None,
                                          C=0.75,
                                          verbose=2,
                                          multi_class="multinomial",
                                          solver="newton-cg",
                                          penalty="l2",
                                          n_jobs=10),
                       "test_submission_part_5_LR.csv")


[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done   1 out of   1 | elapsed:   34.3s finished


fold:0
confusion_mat: [[777 266 107  71  57]
 [253 494 305 119  55]
 [ 72 214 394 205  94]
 [ 34  92 253 473 267]
 [ 26  83 123 304 700]]
macro_f1 0.48232107423081194


[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done   1 out of   1 | elapsed:   36.1s finished


fold:1
confusion_mat: [[820 300 119  55  49]
 [239 481 294  99  52]
 [ 71 269 418 214  82]
 [ 40  94 223 498 237]
 [ 28  54 105 323 674]]
macro_f1 0.49173805437451923


[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done   1 out of   1 | elapsed:   34.2s finished


fold:2
confusion_mat: [[817 253 113  53  45]
 [253 494 281  88  59]
 [ 67 243 425 201  70]
 [ 34  98 273 470 273]
 [ 32  70 124 327 675]]
macro_f1 0.48986483892394955


[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done   1 out of   1 | elapsed:   35.7s finished


fold:3
confusion_mat: [[768 312  96  63  53]
 [266 464 308  92  56]
 [ 81 263 406 216  78]
 [ 40  97 224 447 239]
 [ 30  62 121 333 723]]
macro_f1 0.47667474939236587


[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.


fold:4
confusion_mat: [[841 301  95  56  31]
 [227 476 293 103  56]
 [ 73 280 416 199  67]
 [ 41 120 232 453 270]
 [ 27  79 114 307 680]]
macro_f1 0.48674201849117704


[Parallel(n_jobs=10)]: Done   1 out of   1 | elapsed:   36.4s finished


In [34]:
multicalss_clsfication(features_mc,
                       labels_mc,
                       MLPClassifier(hidden_layer_sizes=(512,256),
                                                        max_iter=500, 
                                                        alpha=0.0001,
                                                        solver='adam',
                                                        random_state=0,
                                                        tol=0.0001,verbose=True),
                       "test_submission_part_5_MLP.csv")

Iteration 1, loss = 1.30886509
Iteration 2, loss = 0.99568896
Iteration 3, loss = 0.80236244
Iteration 4, loss = 0.53189787
Iteration 5, loss = 0.25581912
Iteration 6, loss = 0.12250000
Iteration 7, loss = 0.07927090
Iteration 8, loss = 0.06234768
Iteration 9, loss = 0.05343931
Iteration 10, loss = 0.04881382
Iteration 11, loss = 0.04616399
Iteration 12, loss = 0.04423752
Iteration 13, loss = 0.04168202
Iteration 14, loss = 0.04057117
Iteration 15, loss = 0.03942698
Iteration 16, loss = 0.03841142
Iteration 17, loss = 0.03924785
Iteration 18, loss = 0.03841147
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=multinomial, penalty=l2, solver=lbfgs; total time= 1.2min
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=multinomial, penalty=l2, solver=liblinear; total time=   2.4s
[CV] END C=0.75, class_weight=balanced, max_iter=100, multi_class=multinomial, penalty=l2, solver=liblinear; total time=   1.8s
[CV] END C=0.75, class_weight=balanced, max_iter=100,

# 4. Clustering

In [37]:
# data handling
def transfer(x):
    class_map = {"automotive":0,"CDs":1,"grocery":2,"cell_phones":3,"sports":4,"toys":5,}
    if x in class_map.keys():
        return class_map[x]
    else:
        return x
train["category"]=train["category"].apply(transfer)
train

overall  verified                                         reviewText  \
0            1     False      all of the reviews for this product are fake.   
1            1      True                             wrong part. our fault.   
2            1      True                   this wire set it really sucks!!!   
3            1      True  first use, it leaked instantly. even at 5 buck...   
4            1      True                                         didn't fit   
...        ...       ...                                                ...   
29184        5      True  this is the same plush toy that the official d...   
29185        5      True  my grandson loved this. it is a great toy, he ...   
29186        5      True  my kiddo loves them! we are a rock climbing fa...   
29187        5      True  i bought this for my niece (age 2) and mailed ...   
29188        5      True  my daughter will love this! she's a huge ninja...   

                                                 summary  \
0                              all fake reviews, beware.   
1                                               one star   
2                                               one star   
3                                               one star   
4                                               one star   
...                                                  ...   
29184                        well constructed, very soft   
29185                                            fun toy   
29186   and now the play set has a nice climbing feature   
29187  my brother said she liked it and i haven't see...   
29188                               ninja fan will love!   

                                              style  category  \
0                          {'size:': ' polaris h4'}         0   
1                                               nan         0   
2                                               nan         0   
3      {'color:': ' clear', 'style:': ' 45 degree'}         0   
4                                               nan         0   
...                                             ...       ...   
29184                                           nan         5   
29185                                           nan         5   
29186                                           nan         5   
29187               {'style:': ' standard version'}         5   
29188                                           nan         5   

                                                 alltext  \
0      all fake reviews, beware. all of the reviews f...   
1                    one star wrong part. our fault. nan   
2          one star this wire set it really sucks!!! nan   
3      one star first use, it leaked instantly. even ...   
4                                one star didn't fit nan   
...                                                  ...   
29184  well constructed, very soft this is the same p...   
29185  fun toy my grandson loved this. it is a great ...   
29186  and now the play set has a nice climbing featu...   
29187  my brother said she liked it and i haven't see...   
29188  ninja fan will love! my daughter will love thi...   

                                               allreview  
0      all fake reviews, beware. all of the reviews f...  
1                        one star wrong part. our fault.  
2              one star this wire set it really sucks!!!  
3      one star first use, it leaked instantly. even ...  
4                                    one star didn't fit  
...                                                  ...  
29184  well constructed, very soft this is the same p...  
29185  fun toy my grandson loved this. it is a great ...  
29186  and now the play set has a nice climbing featu...  
29187  my brother said she liked it and i haven't see...  
29188  ninja fan will love! my daughter will love thi...  

[29189 rows x 8 columns]

In [38]:
def eval_mat_kmeans(X,y_true,y_pred):
    silhouette_avg = silhouette_score(X, y_pred)
    rand_index = adjusted_rand_score(y_true, y_pred)
    print("silhouette_score:",silhouette_avg)
    print("rand_index:",rand_index)

In [39]:
vectorizer_kmeans = CountVectorizer(stop_words="english")
transformer_kmeans =TfidfTransformer()
features_kmeans= vectorizer.fit_transform(train["alltext"].values)
features_kmeans = transformer.fit_transform(features_kmeans)
features_kmeans = features_kmeans.toarray()
test_features_kmeans= vectorizer.transform(test["alltext"].values)
test_features_kmeans = transformer.fit_transform(test_features_kmeans)
test_features_kmeans=test_features_kmeans.toarray()

labels_kmeans = train["category"].values

In [40]:
cls = KMeans(6,init="random")

In [41]:
def kmeans(X,y,model:KMeans,test_file_name:str):
    kf = KFold(n_splits=5, shuffle=True)
    for idx,(train_index, test_index) in enumerate(kf.split(X)):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        print("fold:{}".format(idx))
        eval_mat_kmeans(X_test,y_test,y_pred)
    test_predicted = model.predict(test_features_kmeans)
    test_submission = pd.DataFrame({'id':np.arange(len(test_predicted)), 'predicted':test_predicted})
    test_submission.to_csv(test_file_name, index=False)

In [ ]:
kmeans(features_kmeans,labels_kmeans,cls,"test_submission_part_6.csv")